stages: 
    - initial
    - test
    
initial: 
    stage: initial
    script: 
        - echo "Initialize before testing"
        - pip install -r requirements.txt

test:
    stage: test 
    script: 
        - echo "Testing"
        - python manage.py runserver
   