# Generated by Django 3.0.3 on 2020-03-06 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('arrangements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='challenge',
            new_name='challenge_name',
        ),
    ]
