# Generated by Django 3.0.3 on 2020-03-11 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arrangements', '0003_auto_20200307_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='participants',
        ),
        migrations.AddField(
            model_name='challenge',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
