# Generated by Django 3.0.3 on 2020-02-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages1',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='messages1',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='messages1',
            name='text_from',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='messages1',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
